spring.application.name=api-gateway

server.port=8090

# ROUTE MS-MENSAJERIA
spring.cloud.gateway.server.webflux.routes[0].id=ms-mensajeria
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/mensajeria/**

# ROUTE MS-PRECIOS
spring.cloud.gateway.server.webflux.routes[1].id=ms-precios
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8088
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/precios/**

# ROUTE MS-SEGUROS
spring.cloud.gateway.server.webflux.routes[2].id=ms-seguros
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8089
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/seguros/**

